### ISSUE TITLE
'this' is undefined inside inside directive functions

### ISSUE THREAD

**Issue by gitnik** [tengyifei/angular-es6-di#5]
``` javascript
@Directive([userService])
@Name('userList')
export default class UserListDirective extends BaseDirective {
    constructor(UserService) {
        super();

        this.template = '{{ vm.users[0].name }}';

        this.UserService = UserService;
    }

    controller() {
        this.users = this.UserService.getAll();
    }
}
-------
angular.module('app').use(UserListDirective);
```

results in `TypeError: Cannot read property 'getAll' of undefined`which is due to the `this` being undefined in the controller method. After glancing trough the code this is probably because only the compile gets the correct context, when in reality this needs to be done for all methods

**Comment by tengyifei** [comment]
Hmm. My memory regarding directives was a bit flaky after months of not using it. Seems that `UserService` is undefined. Can you print out what's in `this`?

Currently only functions _returned_ by `compile` gets monkey-patched to have `this`. If you return

``` js
{
    controller: this.controller
}
```

in the constructor it will probably work.

**Comment by gitnik** [comment]
Nah the UserService is defined. It's `this` being undefined which is actually not even wrong considering how directives work. Consider the following in ES5:

``` javascript
function someDirective() {
    return {
        restrict: 'E',
        controller: function($scope) {
            this.someThing = "foo";
        },
        someFunction: function() {
            console.log(this.someThing); // this will obviously NOT log foobar
        }
    };
}
```

Now the same in ES6

``` javascript
class SomeDirective {
    constructor() {
        this.restrict = 'E';
    }

    controller($scope) {
        this.something = 'foo';
    }

    someFunction() {
        console.log(this.something); // also logs nothing, which is obvious if you look at the ES5 example
    }
}
```

the problem is that by having directives defined as classes, a developer gets the illusion that everything is accessible via "this" when in reality it's not. he question is, how do you wanna handle this? do the technically "correct" thing and have "this" be different in every function or offer a more convenient functionality that shares the same "this" instance across all class functions

**Comment by tengyifei** [comment]
Ah I see what you're talking about. This is strange. How did you end up calling a function within the directive? Did you inject the directive elsewhere?

**Comment by gitnik** [comment]
No not at all. I just falsely assumed that the constructor and the controller function shared the same context, which is wrong.

**Comment by tengyifei** [comment]
This probably will only happen to `controller()`. Functions not known by Angular get called by the correct context, aren't they?

**Comment by gitnik** [comment]
But functions not known to angular and being called by eg the controller, would also have the wrong context. This whole thing wouldn't be too much of an issue if the library somehow allowed you to inject stuff into the controller

**Comment by tengyifei** [comment]
I see. By injecting stuff into the controller, do you mean injecting dependencies into the `controller()` function inside the directive?

**Comment by gitnik** [comment]
Exactly

**Comment by tengyifei** [comment]
Alright. What about this? (Implementation proposal)

``` js
class Directive {
    @Inject(['$scope'])
    controller ($scope) {
    }
}
```

**Comment by gitnik** [comment]
Yeah I guess something along these lines would work
